git:
  depth: false

language: ruby
cache: bundler

before_install:
  - git checkout 033823b
  - gem update --system --no-document
  - bundle update --bundler

rvm: 2.7
script: bundle exec jekyll build -Vt
